<?php

return [
    'default' => [
        'gradient' => 'from-gray-800 to-gray-900',
        'accent' => 'blue-400',
        'icon' => 'question-mark-circle',
        'background_pattern' => 'none',
        'emoji' => '📋',
        'badge' => '📋',
    ],
    'science' => [
        'gradient' => 'from-indigo-900 to-purple-900',
        'accent' => 'cyan-400',
        'icon' => 'beaker',
        'background_pattern' => 'molecules',
        'emoji' => '🧪',
        'badge' => '⚗️',
    ],
    'nature' => [
        'gradient' => 'from-green-900 to-emerald-900',
        'accent' => 'lime-400',
        'icon' => 'leaf',
        'background_pattern' => 'leaves',
        'emoji' => '🦋',
        'badge' => '🌿',
    ],
    'history' => [
        'gradient' => 'from-amber-900 to-yellow-900',
        'accent' => 'amber-300',
        'icon' => 'book-open',
        'background_pattern' => 'parchment',
        'emoji' => '🏛️',
        'badge' => '⚜',
    ],
    'pop-culture' => [
        'gradient' => 'from-pink-900 to-rose-900',
        'accent' => 'pink-400',
        'icon' => 'star',
        'background_pattern' => 'stars',
        'emoji' => '🎤',
        'badge' => '★',
    ],
    'sports' => [
        'gradient' => 'from-red-900 to-orange-900',
        'accent' => 'orange-400',
        'icon' => 'trophy',
        'background_pattern' => 'field',
        'emoji' => '⚽',
        'badge' => '🏆',
    ],
    'geography' => [
        'gradient' => 'from-sky-900 to-blue-900',
        'accent' => 'sky-400',
        'icon' => 'globe-alt',
        'background_pattern' => 'map',
        'emoji' => '🗺️',
        'badge' => '🧭',
    ],
    'general-knowledge' => [
        'gradient' => 'from-indigo-900 to-blue-900',
        'accent' => 'indigo-400',
        'icon' => 'light-bulb',
        'background_pattern' => 'none',
        'emoji' => '🧠',
        'badge' => '💡',
    ],
];
